gitflow merge with automatic message

diff --git a/git-flow-update b/git-flow-update
--- a/git-flow-update
+++ b/git-flow-update
@@ -73,7 +73,6 @@ cmd_list() {
                 warn ""
 		exit 0
 	fi
-
 	current_branch=$(git branch --no-color | grep '^\* ' | grep -v 'no branch' | sed 's/^* //g')
 	short_names=$(echo "$update_branches" | sed "s ^$PREFIX  g")
 
@@ -186,115 +185,10 @@ cmd_start() {
 	echo
 	echo "Follow-up actions:"
 	echo "- Bump the version number now!"
-	echo "- Start committing last-minute fixes in preparing your update release"
+	echo "- Start committing your update release"
 	echo "- When done, run:"
 	echo
 	echo "     git flow update finish '$VERSION'"
-	echo
-}
-
-cmd_finish() {
-	DEFINE_boolean fetch false "fetch from $ORIGIN before performing finish" F
-	DEFINE_boolean sign false "sign the update release tag cryptographically" s
-	DEFINE_string signingkey "" "use the given GPG-key for the digital signature (implies -s)" u
-	DEFINE_string message "" "use the given tag message" m
-	DEFINE_string messagefile "" "use the contents of the given file as a tag message" f
-	DEFINE_boolean push false "push to $ORIGIN after performing finish" p
-	DEFINE_boolean keep false "keep branch after performing finish" k
-	DEFINE_boolean notag false "don't tag this update release" n
-	DEFINE_boolean squash false "squash update release during merge" S
-
-	parse_args "$@"
-	require_version_arg
-
-	# handle flags that imply other flags
-	if [ "$FLAGS_signingkey" != "" ]; then
-		FLAGS_sign=$FLAGS_TRUE
-	fi
-
-	# sanity checks
-	require_branch "$BRANCH"
-	require_clean_working_tree
-	if flag fetch; then
-		git_do fetch -q "$ORIGIN" "$MASTER_BRANCH" || \
-		  die "Could not fetch $MASTER_BRANCH from $ORIGIN."
-	fi
-	if has "$ORIGIN/$MASTER_BRANCH" $(git_remote_branches); then
-		require_branches_equal "$MASTER_BRANCH" "$ORIGIN/$MASTER_BRANCH"
-	fi
-
-	if noflag notag; then
-		# try to tag the update release
-		# in case a previous attempt to finish this update release branch has failed,
-		# but the tag was set successful, we skip it now
-		local tagname=$VERSION_PREFIX$VERSION
-		if ! git_tag_exists "$tagname"; then
-			local opts="-a"
-			flag sign && opts="$opts -s"
-			[ "$FLAGS_signingkey" != "" ] && opts="$opts -u '$FLAGS_signingkey'"
-			[ "$FLAGS_message" != "" ] && opts="$opts -m '$FLAGS_message'"
-			[ "$FLAGS_messagefile" != "" ] && opts="$opts -F '$FLAGS_messagefile'"
-			eval git_do tag $opts "$tagname" "$BRANCH" || \
-			die "Tagging failed. Please run finish again to retry."
-		fi
-	fi
-
-	# try to merge into master
-	# in case a previous attempt to finish this update release branch has failed,
-	# but the merge into master was successful, we skip it now
-	if ! git_is_branch_merged_into "$BRANCH" "$MASTER_BRANCH"; then
-		git_do checkout "$MASTER_BRANCH" || \
-		  die "Could not check out $MASTER_BRANCH."
-
-		# TODO: Actually, accounting for 'git describe' pays, so we should
-		# ideally git merge --no-ff $tagname here, instead!
-		if noflag squash; then
-			git_do merge --no-ff "$BRANCH" || \
-				die "There were merge conflicts."
-				# TODO: What do we do now?
-		else
-			git_do merge --squash "$BRANCH" || \
-				die "There were merge conflicts."
-				# TODO: What do we do now?
-			git_do commit
-		fi
-	fi
-
-	# delete branch
-	if noflag keep; then
-		if [ "$BRANCH" = "$(git_current_branch)" ]; then
-			git_do checkout "$MASTER_BRANCH"
-		fi
-		git_do branch -d "$BRANCH"
-	fi
-
-	if flag push; then
-		git_do push "$ORIGIN" "$MASTER_BRANCH" || \
-			die "Could not push to $MASTER_BRANCH from $ORIGIN."
-		if noflag notag; then
-			git_do push --tags "$ORIGIN" || \
-			  die "Could not push tags to $ORIGIN."
-		fi
-		git_do push "$ORIGIN" :"$BRANCH" || \
-			die "Could not delete the remote $BRANCH in $ORIGIN."
-	fi
-
-	echo
-	echo "Summary of actions:"
-	echo "- Latest objects have been fetched from '$ORIGIN'"
-	if noflag notag; then
-		echo "- The update release was tagged '$tagname'"
-	fi
-	echo "- Update branch has been back-merged into '$MASTER_BRANCH'"
-	if flag keep; then
-		echo "- Update branch '$BRANCH' is still available"
-	else
-		echo "- Update branch '$BRANCH' has been deleted"
-	fi
-	if flag push; then
-		echo "- '$MASTER_BRANCH' and tags have been pushed to '$ORIGIN'"
-		echo "- Update branch '$BRANCH' in '$ORIGIN' has been deleted."
-	fi
 	echo
 }
 
@@ -313,8 +207,8 @@ cmd_publish() {
 	git_do fetch -q "$ORIGIN"
 
 	# configure remote tracking
-	git_do config "branch.$BRANCH.remote" "$ORIGIN"
-	git_do config "branch.$BRANCH.merge" "refs/heads/$BRANCH"
+	git config "branch.$BRANCH.remote" "$ORIGIN"
+	git config "branch.$BRANCH.merge" "refs/heads/$BRANCH"
 	git_do checkout "$BRANCH"
 
 	echo
@@ -342,5 +236,119 @@ cmd_track() {
 	echo "Summary of actions:"
 	echo "- A new remote tracking branch '$BRANCH' was created"
 	echo "- You are now on branch '$BRANCH'"
+	echo
+}
+
+cmd_finish() {
+	DEFINE_boolean fetch false "fetch from $ORIGIN before performing finish" F
+	DEFINE_boolean sign false "sign the update release tag cryptographically" s
+	DEFINE_string signingkey "" "use the given GPG-key for the digital signature (implies -s)" u
+	DEFINE_string message "" "use the given tag message" m
+	DEFINE_string messagefile "" "use the contents of the given file as a tag message" f
+	DEFINE_boolean push false "push to $ORIGIN after performing finish" p
+	DEFINE_boolean keep false "keep branch after performing finish" k
+	DEFINE_boolean notag false "don't tag this update release" n
+	DEFINE_boolean squash false "squash update release during merge" S
+	parse_args "$@"
+	require_version_arg
+
+	# handle flags that imply other flags
+	if [ "$FLAGS_signingkey" != "" ]; then
+		FLAGS_sign=$FLAGS_TRUE
+	fi
+
+	# sanity checks
+	require_branch "$BRANCH"
+	require_clean_working_tree
+	if flag fetch; then
+		git_do fetch -q "$ORIGIN" "$MASTER_BRANCH" || \
+		  die "Could not fetch $MASTER_BRANCH from $ORIGIN."
+		git_do fetch -q "$ORIGIN" "$DEVELOP_BRANCH" || \
+		  die "Could not fetch $DEVELOP_BRANCH from $ORIGIN."
+	fi
+	if has "$ORIGIN/$MASTER_BRANCH" $(git_remote_branches); then
+		require_branches_equal "$MASTER_BRANCH" "$ORIGIN/$MASTER_BRANCH"
+	fi
+	if has "$ORIGIN/$DEVELOP_BRANCH" $(git_remote_branches); then
+		require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
+	fi
+
+	# try to merge into master
+	# in case a previous attempt to finish this release branch has failed,
+	# but the merge into master was successful, we skip it now
+	if ! git_is_branch_merged_into "$BRANCH" "$MASTER_BRANCH"; then
+		git_do checkout "$MASTER_BRANCH" || \
+		  die "Could not check out $MASTER_BRANCH."
+		#git_do merge --no-ff "$BRANCH" || \
+    git_do merge -m "Merge branch $BRANCH" --no-ff "$BRANCH" || \
+		  die "There were merge conflicts."
+		  # TODO: What do we do now?
+	fi
+  
+	if noflag notag; then
+		# try to tag the update release
+		# in case a previous attempt to finish this update release branch has failed,
+		# but the tag was set successful, we skip it now
+		local tagname=$VERSION_PREFIX$VERSION
+		if ! git_tag_exists "$tagname"; then
+			local opts="-a"
+			flag sign && opts="$opts -s"
+			[ "$FLAGS_signingkey" != "" ] && opts="$opts -u '$FLAGS_signingkey'"
+			[ "$FLAGS_message" != "" ] && opts="$opts -m '$FLAGS_message'"
+			[ "$FLAGS_messagefile" != "" ] && opts="$opts -F '$FLAGS_messagefile'"
+			eval git_do tag $opts "$tagname" "$BRANCH" || \
+			die "Tagging failed. Please run finish again to retry."
+		fi
+	fi
+
+	# try to merge into develop
+	# in case a previous attempt to finish this release branch has failed,
+	# but the merge into develop was successful, we skip it now
+	if ! git_is_branch_merged_into "$BRANCH" "$DEVELOP_BRANCH"; then
+		git_do checkout "$DEVELOP_BRANCH" || \
+		  die "Could not check out $DEVELOP_BRANCH."
+		#git_do merge --no-ff "$BRANCH" || \
+    git_do merge -m "Merge branch $BRANCH" --no-ff "$BRANCH" || \
+		  die "There were merge conflicts."
+		  # TODO: What do we do now?
+	fi
+
+	# delete branch
+	if noflag keep; then
+		if [ "$BRANCH" = "$(git_current_branch)" ]; then
+			git_do checkout "$MASTER_BRANCH"
+		fi
+		git_do branch -d "$BRANCH"
+	fi
+
+	if flag push; then
+		git_do push "$ORIGIN" "$DEVELOP_BRANCH" || \
+			die "Could not push to $DEVELOP_BRANCH from $ORIGIN."
+		git_do push "$ORIGIN" "$MASTER_BRANCH" || \
+			die "Could not push to $MASTER_BRANCH from $ORIGIN."
+		if noflag notag; then
+			git_do push --tags "$ORIGIN" || \
+				die "Could not push tags to $ORIGIN."
+		fi
+		git_do push "$ORIGIN" :"$BRANCH" || \
+			die "Could not delete the remote $BRANCH in $ORIGIN."
+	fi
+
+	echo
+	echo "Summary of actions:"
+	echo "- Latest objects have been fetched from '$ORIGIN'"
+  echo "- Update branch has been merged into '$MASTER_BRANCH'"
+	if noflag notag; then
+		echo "- The update release was tagged '$tagname'"
+	fi
+	echo "- Update branch has been back-merged into '$DEVELOP_BRANCH'"
+	if flag keep; then
+		echo "- Update branch '$BRANCH' is still available"
+	else
+		echo "- Update branch '$BRANCH' has been deleted"
+	fi
+	if flag push; then
+		echo "- '$DEVELOP_BRANCH', '$MASTER_BRANCH' and tags have been pushed to '$ORIGIN'"
+	fi
 	echo
 }
